### ISSUE TITLE
Black list all phones 

### ISSUE THREAD

**Issue by Ryankay07** [bayuperkasa345/agariobot#1]
[10/08/2024, 08:04:05] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 08:04:20] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 08:04:35] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 08:04:50] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 08:05:00] [homebridge-ring] Error: 
    at responseToError (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:38:19)
    at requestWithRetry (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:82:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:201:73) {
  response: {
    headers: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    status: 401,
    body: {
      error: 'invalid_grant',
      error_description: 'The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.'
    }
  }
}
[10/08/2024, 08:05:00] [homebridge-ring] Request to https://api.ring.com/devices/v1/locations failed:
[10/08/2024, 08:05:00] [homebridge-ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:196:15)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:199:32)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:240:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[10/08/2024, 08:05:00] [homebridge-ring] Error connecting to API
[10/08/2024, 08:05:00] [homebridge-ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:196:15)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:199:32)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:240:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[10/08/2024, 08:08:24] [homebridge-ring] Launched child bridge with PID 7287
[10/08/2024, 08:08:25] Loaded 0 cached accessories from cachedAccessories.0E49C066B5E8.
[10/08/2024, 08:08:33] [homebridge-ring] Loaded homebridge-ring v13.0.1 child bridge successfully
[10/08/2024, 08:08:33] Loaded 0 cached accessories from cachedAccessories.0E7B1913CD5B.
[10/08/2024, 08:08:44] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 08:08:59] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 08:09:14] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 08:09:29] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 08:09:39] [homebridge-ring] Error: 
    at responseToError (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:38:19)
    at requestWithRetry (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:82:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:201:73) {
  response: {
    headers: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    status: 401,
    body: {
      error: 'invalid_grant',
      error_description: 'The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.'
    }
  }
}
[10/08/2024, 08:09:39] [homebridge-ring] Request to https://api.ring.com/devices/v1/locations failed:
[10/08/2024, 08:09:39] [homebridge-ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:196:15)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:199:32)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:240:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[10/08/2024, 08:09:39] [homebridge-ring] Error connecting to API
[10/08/2024, 08:09:39] [homebridge-ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:196:15)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:199:32)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:240:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[10/08/2024, 08:24:16] [homebridge-ring] Launched child bridge with PID 7830
[10/08/2024, 08:24:25] [homebridge-ring] Loaded homebridge-ring v13.0.1 child bridge successfully
[10/08/2024, 08:24:36] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 08:24:51] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 08:25:06] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 08:25:21] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 08:25:31] [homebridge-ring] Error: 
    at responseToError (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:38:19)
    at requestWithRetry (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:82:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:201:73) {
  response: {
    headers: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    status: 401,
    body: {
      error: 'invalid_grant',
      error_description: 'The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.'
    }
  }
}
[10/08/2024, 08:25:31] [homebridge-ring] Request to https://api.ring.com/devices/v1/locations failed:
[10/08/2024, 08:25:31] [homebridge-ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:196:15)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:199:32)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:240:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[10/08/2024, 08:25:31] [homebridge-ring] Error connecting to API
[10/08/2024, 08:25:31] [homebridge-ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:196:15)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:199:32)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:240:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[10/08/2024, 08:29:35] [homebridge-ring] Launched child bridge with PID 8138
[10/08/2024, 08:29:43] [homebridge-ring] Loaded homebridge-ring v13.0.1 child bridge successfully
[10/08/2024, 08:29:54] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 08:30:09] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 08:30:39] [homebridge-ring] Launched child bridge with PID 8308
[10/08/2024, 08:30:39] Loaded 2 cached accessories from cachedAccessories.0E3B54C8AD41.
[10/08/2024, 08:30:39] Loaded 13 cached accessories from cachedAccessories.0EAC5DC796E1.
[10/08/2024, 08:30:49] [homebridge-ring] Loaded homebridge-ring v13.0.1 child bridge successfully
[10/08/2024, 08:30:49] Loaded 0 cached accessories from cachedAccessories.0E7B1913CD5B.
[10/08/2024, 08:31:00] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 08:31:15] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 08:31:30] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 08:31:45] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 08:31:56] [homebridge-ring] Error: 
    at responseToError (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:38:19)
    at requestWithRetry (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:82:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:201:73) {
  response: {
    headers: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    status: 401,
    body: {
      error: 'invalid_grant',
      error_description: 'The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.'
    }
  }
}
[10/08/2024, 08:31:56] [homebridge-ring] Request to https://api.ring.com/devices/v1/locations failed:
[10/08/2024, 08:31:56] [homebridge-ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:196:15)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:199:32)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:240:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[10/08/2024, 08:31:56] [homebridge-ring] Error connecting to API
[10/08/2024, 08:31:56] [homebridge-ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:196:15)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:199:32)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:240:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Te Anau front 244F] The image snapshot handler for the given accessory is slow to respond! See https://homebridge.io/w/JtMGR for more info.
[10/08/2024, 10:01:07] [homebridge-ring] Launched child bridge with PID 10558
[10/08/2024, 10:01:16] [homebridge-ring] Loaded homebridge-ring v13.0.1 child bridge successfully
[10/08/2024, 10:01:16] Loaded 0 cached accessories from cachedAccessories.0E7B1913CD5B.
[10/08/2024, 10:01:27] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 10:01:42] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 10:01:57] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 10:02:12] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 10:02:22] [homebridge-ring] Error: 
    at responseToError (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:38:19)
    at requestWithRetry (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:82:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:201:73) {
  response: {
    headers: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    status: 401,
    body: {
      error: 'invalid_grant',
      error_description: 'The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.'
    }
  }
}
[10/08/2024, 10:02:22] [homebridge-ring] Request to https://api.ring.com/devices/v1/locations failed:
[10/08/2024, 10:02:22] [homebridge-ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:196:15)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:199:32)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:240:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[10/08/2024, 10:02:22] [homebridge-ring] Error connecting to API
[10/08/2024, 10:02:22] [homebridge-ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:196:15)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:199:32)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:240:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[10/08/2024, 10:04:51] [homebridge-ring] Launched child bridge with PID 10994
[10/08/2024, 10:05:00] [homebridge-ring] Loaded homebridge-ring v13.0.1 child bridge successfully
[10/08/2024, 10:05:11] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 10:05:26] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 10:05:41] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 10:05:56] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[10/08/2024, 10:06:07] [homebridge-ring] Error: 
    at responseToError (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:38:19)
    at requestWithRetry (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:82:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:201:73) {
  response: {
    headers: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    status: 401,
    body: {
      error: 'invalid_grant',
      error_description: 'The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.'
    }
  }
}
[10/08/2024, 10:06:07] [homebridge-ring] Request to https://api.ring.com/devices/v1/locations failed:
[10/08/2024, 10:06:07] [homebridge-ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:196:15)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:199:32)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:240:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[10/08/2024, 10:06:07] [homebridge-ring] Error connecting to API
[10/08/2024, 10:06:07] [homebridge-ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:196:15)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:199:32)
    at RingRestClient.getAuth (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js:240:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/08/2024, 06:48:08] [homebridge-ring] Launched child bridge with PID 35585
[11/08/2024, 06:48:17] [homebridge-ring] Loaded homebridge-ring v13.0.1 child bridge successfully
[11/08/2024, 06:48:18] Loaded 0 cached accessories from cachedAccessories.0E7B1913CD5B.
[11/08/2024, 06:48:28] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[11/08/2024, 06:48:43] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...
[11/08/2024, 06:48:58] [homebridge-ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch failed.  Trying again in 5 seconds...

**Comment by Ryankay07** [comment]
Knock all databases to cell phones
